### ISSUE TITLE
Ambiguous rule matches on transformation

### ISSUE THREAD

**Issue by chrxr** [andrgosl/PUK_XProc_Dev#1]
Transforming Sample doc 2, getting "Transformation Problems" warning messages:

System ID: /Users/chriroge/PUK_XProc_Dev/ms-word-to-xml/xproc/word2db.xpl
Scenario: page_005
XProc file: /Users/chriroge/PUK_XProc_Dev/ms-word-to-xml/xproc/word2db.xpl
Engine name: Calabash XProc
Severity: warning
Description:  Ambiguous rule match for /word-doc/w:document[1]/w:body[1]/w:p[12]
Matches both "w:p[count(w:r) = 1 and w:r/w:tab]" on line 141 of file:/Users/chriroge/PUK_XProc_Dev/ms-word-to-xml/xsl/word-components.xsl
and "w:p[not(normalize-space(.) = '')]" on line 77 of file:/Users/chriroge/PUK_XProc_Dev/ms-word-to-xml/xsl/word-components.xsl

**Comment by nic-gibson** [comment]
That's a partially implemented fixup. Should be resolved in the next update.

**Comment by nic-gibson** [comment]
Corrected in current version
