### ISSUE TITLE
Line 324 Full sample - apple-converted-space and apple-style-span?

### ISSUE THREAD

**Issue by chrxr** [andrgosl/PUK_XProc_Dev#10]
These styles seem to appear randomly on phrase tags.

**Comment by andrgosl** [comment]
leave for now, but perhaps consider stripping non-standard styles if we can create a definitive list

**Comment by nic-gibson** [comment]
These are styles inherited with smart pasting across apps. Either we create a list of all valid styles or we live with it. They will have no effect in the output.
