### ISSUE TITLE
some concatenated words are appearing

### ISSUE THREAD

**Issue by chrxr** [andrgosl/PUK_XProc_Dev#11]
For example line 2181 of xml generated from Penguin-sample-full-edit ("foodthat"). Suspect it is something to do with this code in document.xml:

```
...expression of that food</w:t>
        </w:r>
        <w:r>
            <w:t xml:space="preserve"> </w:t>
        </w:r>
        <w:r w:rsidRPr="00324ACC">
            <w:t>that can justify...
```

Looks like that <w:t> element is being stripped resulting in the space it contains being lost. This happens quite regularly throughout the manuscript.

**Comment by nic-gibson** [comment]
You may well be right there. I've been very careful to deal with xml:space but text with just one space may be problematic. Let me check.

nic

On 13 Jul 2012, at 12:06, chrxr wrote:

> For example line 2181 of xml generated from Penguin-sample-full-edit ("foodthat"). Suspect it is something to do with this code in document.xml:
> 
>    ...expression of that food/w:t
>            /w:r
>            <w:r>
>                <w:t xml:space="preserve"> /w:t
>            /w:r
>            <w:r w:rsidRPr="00324ACC">
>                <w:t>that can justify...
> 
> Looks like that <w:t> element is being stripped resulting in the space it contains being lost. This happens quite regularly throughout the manuscript.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/andrgosl/PUK_XProc_Dev/issues/11

## 

Corbas Consulting / @CorbasLtd
Digital Publishing Consultancy and Training
http://www.corbas.co.uk, +44 (0)7718 906817/+44 (0)1273 930765

**Comment by nic-gibson** [comment]
Resolved. The xml:space checking code was written such that it would fail if and only if the w:t element contained just one space.
