### ISSUE TITLE
EPUB: Content files should be XHTML

### ISSUE THREAD

**Issue by chrxr** [andrgosl/PUK_XProc_Dev#13]
Our EPUB tech spec stipulates that we should use xhtml files rather than html files.

**Comment by nic-gibson** [comment]
They are xhtml files

nic

**Comment by chrxr** [comment]
sorry I should have said 'should use the xhtml file extension'

**Comment by nic-gibson** [comment]
OK. That's a bit silly - we should change that perhaps

nic

**Comment by chrxr** [comment]
Let's talk about it later. Change was implemented under the advice of ThreePress for the last tech spec update.

Have a good weekend!
Chris

**Comment by nic-gibson** [comment]
weird. the suffix means precisely nothing :)

nic

**Comment by chrxr** [comment]
Yeah its a consistency thing. Had to plump for one or the other, and xhtml won out.

**Comment by nic-gibson** [comment]
Slightly weird - makes testing hard as no browser associates 'xhtml' with itself :)

nic

**Comment by chrxr** [comment]
Turns out it's in the EPUB3 spec: http://idpf.org/epub/30/spec/epub30-contentdocs.html#sec-xhtml-conf-content

**Comment by nic-gibson** [comment]
If not parameterised I'll make it so.

**Comment by nic-gibson** [comment]
Done
