### ISSUE TITLE
EPUB: copyright page duplicated

### ISSUE THREAD

**Issue by chrxr** [andrgosl/PUK_XProc_Dev#15]
The copyright page has been appended to the end of chapter006.html as well as in it's own file at the end of the book.

**Comment by chrxr** [comment]
Actually not being duplicated. Is the inserted copyright file boiler-plate? It's different from the page appended to the end of Chapter 6, which is title specific.

**Comment by nic-gibson** [comment]
Looks like the old code had a hard coded boiler plate - will correct.

**Comment by nic-gibson** [comment]
Fixed
