### ISSUE TITLE
Cover image assignment

### ISSUE THREAD

**Issue by andrgosl** [andrgosl/PUK_XProc_Dev#17]
We need to generate the the appropriate XML structure in the Docbook XML file the cover image. 

Perhaps we can be able to set the location of the cover image as an option in the word2xml xproc?

**Comment by nic-gibson** [comment]
Done

**Comment by andrgosl** [comment]
great, but the cover image isn't getting transfered to the EPUB output - which is odd. 

my image-root option is set as follows, 

file:/Users/andreas/Dropbox/PUK_XProc_Dev/ms-word-to-xml/images/

and there is cover.jpg in that directory

If I remove or rename this image in that directory Oxygen calabash gives me a cannot copy file not found error, so i think the paths are correct and there is some other problem.

**Comment by andrgosl** [comment]
id for html not being added to opf spine, which is why cover image not displaying. Does in fact copy fine.

**Comment by nic-gibson** [comment]
Id added. Corrected.
