### ISSUE TITLE
docbook metadata

### ISSUE THREAD

**Issue by andrgosl** [andrgosl/PUK_XProc_Dev#18]
We agreed to add info block elements with dummy text for the required epub package data in the docbook XML - e.g. ISBN, Author, Title.

**Comment by nic-gibson** [comment]
Done.

**Comment by andrgosl** [comment]
should have added we also need author, title, isbn metadata included in the opf, which isn't happening at the moment.

**Comment by nic-gibson** [comment]
Fixed
