### ISSUE TITLE
ISBN should be the epub output filenmae

### ISSUE THREAD

**Issue by andrgosl** [andrgosl/PUK_XProc_Dev#19]
Once we have the ISBN in the DocBook XML, it would be good to have it written to the epub output file name, in the format

[ISBN]_EPUB.epub

don't ask about the '_EPUB'. :)

**Comment by nic-gibson** [comment]
I'll need to think about that but it should be possible. The current mechanism uses a parameter for the epub file name.

And... no worries about the _EPUB. I know :)

**Comment by nic-gibson** [comment]
Scripts have been updated to handle this now. The isbn must be in the first biblioid element in the docbook info element and MUST have the class 'isbn' (e.g. <biblioid class='isbn'>9780123456789</biblioid>.

Please change the use of the epub-path option to be the directory into which the EPUB file should be placed.
