### ISSUE TITLE
"About the Author" case lost

### ISSUE THREAD

**Issue by chrxr** [andrgosl/PUK_XProc_Dev#2]
Title for the "About the author", styled in smallcaps, has been captured in lower case in xml.
I can see that it has been entered in lowercase in the example word file, then given a smallcaps style. This will not port well to EPUB as many devices do not support smallcaps, will just display as lowercase.

In our ebook style guidelines we propose that smallcaps are simply captured as uppercase then made smaller via css.

**Comment by nic-gibson** [comment]
This is much better done at the XSLT conversion to HTML stage. Otherwise we end up creating something where we have a rendering requirement at the semantic layer. That means that, if other readers start to resolve the issue then we have a hack in at the wrong place

**Comment by nic-gibson** [comment]
Shoul be fixed now.  Please test and close if fixed

**Comment by chrxr** [comment]
Hi Nic,

text is rendering in lowercase now, but unfortunately the wrong style is being applied. Rendering as h2.EB04MainHead, but should be h5.EB07SmallCapsMediumHead.

**Comment by chrxr** [comment]
This will cause problems in the XHTML and NCX TOCs. They will appear either as all uppercase or all lowercase. They should be normal case(?).
