### ISSUE TITLE
use of epigraph makes 2 preface blocks in XML output

### ISSUE THREAD

**Issue by andrgosl** [andrgosl/PUK_XProc_Dev#20]
I've updated the manuscript (penguin-sample-full-edit.docm) to use the Chapter Epigraph style and Attribution style for the Allen Lane quote at the start document.

This is causing 2 preface blocks to be created, one with just the title, and the second with no title and starting with the epigraph.

**Comment by nic-gibson** [comment]
Have written better code to handle prelims and end matter. Working now for test docs (with one oddity - end matter with front matter style will be marked up as a preface)
