### ISSUE TITLE
hyperlinks to bookmarks to transforming to link

### ISSUE THREAD

**Issue by andrgosl** [andrgosl/PUK_XProc_Dev#21]
I have added a hyperlink to a bookmark in penguin-sample-full-edit.docm. 

The output in the docbook xml isn't quite right - the w:hyperlink element is being output - not transformed to a docbook link.

**Comment by nic-gibson** [comment]
Ahhh. Word. Lovely. According to the spec it should be using a bookmark element to handle that. Fixed.

**Comment by andrgosl** [comment]
Better, but the when you look at the XML output you will see that the linked text 'Shumi' is being omitted. If you delete  the comments this is clearer. Thanks

**Comment by nic-gibson** [comment]
My mistake - did something stupid. Just dealing with the interconnectedness of everything and I'll upload the fix.

## nic

Corbas Consulting / @CorbasLtd
Digital Publishing Consultancy and Training
http://www.corbas.co.uk, +44 (0)7718 906817/+44 (0)1273 930765

**Comment by andrgosl** [comment]
Brill, works a treat. closing.
