### ISSUE TITLE
Transformation from DB to EPUB not working

### ISSUE THREAD

**Issue by chrxr** [andrgosl/PUK_XProc_Dev#23]
With Penguin_sample_full_edit.docm

Description:  Processing terminated by xsl:message at line 489 in xml-to-html.xsl
Start location: 489:0

Line 489:

```
<xsl:template match="*">
    <xsl:message terminate="yes">Unhandled element - <xsl:value-of select="local-name()"
        /></xsl:message>
 </xsl:template>
```

**Comment by nic-gibson** [comment]
Fair enough. Can you get the full message from the input? There should be a saxon message a few lines further back telling me which element isn't currently handled.

**Comment by chrxr** [comment]
Sorry, not sure how to do that, Oxygen error message only includes the above text.

**Comment by nic-gibson** [comment]
Double click or something in oxygen to view while message

## 

Corbas - Digital Publishing Consultancy and Training
http://www.corbas.co.uk/
+44 (0)7718 906817

**Comment by chrxr** [comment]
No, I'm afraid that just opens the xml-to-html.xsl file, and highlights the code mentioned above.

**Comment by nic-gibson** [comment]
I'm getting it integrated into oXygen for me so I can try the same.

**Comment by nic-gibson** [comment]
Hah. Done it and you're right - it fails to show the actual underlying error.

**Comment by nic-gibson** [comment]
Corrected - there was no support in the xml -> html conversion for the remark element I added yesterday.
