### ISSUE TITLE
Order of content for ebooks

### ISSUE THREAD

**Issue by chrxr** [andrgosl/PUK_XProc_Dev#26]
**Black and White without illustrations**
Facsimile of Original Cover
Digital Brand Page
Title Page
Contents Page
About the Author
By the Same Author
Dedication Page
Introduction
Main Body Text
Author Notes
Notes
Bibliography
Glossary
Acknowledgements
Copyright Page
Read More (extra chapter)
Endpages
Footnotes
Endnotes

**Black and White with illustrations**
Facsimile of Original Cover
Digital Brand Page
Title Page
Contents Page
About the Author
By the Same Author
Dedication Page
List of Plates
List of Illustrations
Introduction
Main Body Text
Bibliography
Notes
Chronology
Glossary
Acknowledgements
Copyright Page
Endpages
Footnotes
Endnotes

**Comment by nic-gibson** [comment]
Do the Penguin Shorts need to be reordered from the word file then?

## 

Corbas Consulting / @CorbasLtd
Digital Publishing Consultancy and Training
http://www.corbas.co.uk, +44 (0)7718 906817/+44 (0)1273 930765
