### ISSUE TITLE
Footnotes / endnotes failing

### ISSUE THREAD

**Issue by chrxr** [andrgosl/PUK_XProc_Dev#27]
Word footnotes / endnotes are not being handled well. Footnote ref is being inserted with:

```
<phrase role="FootnoteReference">
    <w:footnoteReference
                   (Loads of Word style namespaces )  />
</phrase>
```

but the footnote content itself is not being pulled in.

Endnote is just the <w:endnote> element without the enclosing phrase.

EPUB conversion fails due to unhandled element.

**Comment by nic-gibson** [comment]
Corrected in latest revision

**Comment by chrxr** [comment]
Hi Nic,

Usually our style guidelines dictate that endnotes and footnotes should be in seperate files at the end of the book. Each chapter should have it's own footnotes page (if it has footnotes), then one chapter with all the endnotes. Is this possible here?

**Comment by nic-gibson** [comment]
No problem. Will take me a hour or to. I have a few other things I want to do over the weekend on it anyway - hoping to get all the issues cleared over the weekend.

## nic

Corbas Consulting / @CorbasLtd
Digital Publishing Consultancy and Training
http://www.corbas.co.uk, +44 (0)7718 906817/+44 (0)1273 930765

**Comment by chrxr** [comment]
Working in the file now, but I'm afraid I didn't remember to check, what's being registered in the NCX for the footnote chapters? Really we just want one entry for the first footnote file.

**Comment by chrxr** [comment]
Currently doesn't pass epubcheck as footnotes and endnotes pages in NCX are the same.
Also both are called Notes in the NCX. Is this the best we can do? If so I'd recommend leaving them out as it looks a little like an error.

I tried to add another footnote into a later chapter, and I’m getting the error below when converting from DB to EPUB: 

System ID: /Users/chriroge/Documents/workspace/PUK_XML_EPUB/ms-word-to-xml/xsl/docbook-to-epub/page-ids.xsl
Scenario: XML to epub
XProc file: /Users/chriroge/Documents/workspace/PUK_XML_EPUB/ms-word-to-xml/xproc/create-epub.xpl
Engine name: Calabash XProc
Severity: error
Description:  A sequence of more than one item is not allowed as the first argument of local-name() (<preface/>, <chapter/>) 
Start location: 30:0

**Comment by chrxr** [comment]
Almost there.

Small problem with endnote numbering, they should go up continuously throughout the book, not restart at each chapter (as opposed to footnotes, which should restart at each chapter).

**Comment by chrxr** [comment]
Woops closed by accident

**Comment by nic-gibson** [comment]
Oh. Drat. Will fix in coffee break (at #xmlss12 today)

## nic

Corbas Consulting / @CorbasLtd
Digital Publishing Consultancy and Training
http://www.corbas.co.uk, +44 (0)7718 906817/+44 (0)1273 930765

**Comment by nic-gibson** [comment]
Numbering corrected and back links fixed

**Comment by chrxr** [comment]
Hi Nic,

So very, very close. The endnotes are now awesome. Problem though is occuring with footnotes. If an endnote occurs before a footnote in the same chapter, the endnote numbers correctly but the footnote will be one more than it should be. I've updated the manuscript to demonstrate.

C
