### ISSUE TITLE
Acknowledgements and inline-footnote style mapping

### ISSUE THREAD

**Issue by chrxr** [andrgosl/PUK_XProc_Dev#28]
New version of sample doc uploaded to github with additional styles

Acknowledgements head (and 01FMHead) should be mapped to h2.EB04MainHead

"Inline footnote only" style should be mapped to p.EB19ExtraFeatureFullOut

**Comment by nic-gibson** [comment]
All bar Inline Footnote in current buold

**Comment by nic-gibson** [comment]
Done. Please check.
