### ISSUE TITLE
dedication element in XML should be top level element

### ISSUE THREAD

**Issue by chrxr** [andrgosl/PUK_XProc_Dev#29]
Currently, when using the dedication style, the resulting dedication element is placed within the last top level element (likely preface). Dedication should be a top-level element on it's own.

Manually moving the dedication element and converting to epub results in a chapter names 01FMDediBody.html

New sample uploaded including dedication.

**Comment by chrxr** [comment]
Dedication is appearing in the wrong place in the epub, just after the TOC, whereas in the word doc it is after the acknowledgements.

**Comment by nic-gibson** [comment]
Been looking at dedications again. The problem we are seeing is caused by the fact that dedications can't go just anywhere in DocBook. I can't make it a preface without giving it a title either. Let's have a phone chat about how to handle this?
