### ISSUE TITLE
Line 267 - 277, 15Italic captured as ColorfulList-Accent11

### ISSUE THREAD

**Issue by chrxr** [andrgosl/PUK_XProc_Dev#3]
Whole para should be 15Italic?
15Italic is appearing in random phrases some of which start and end in the middle of words

**Comment by nic-gibson** [comment]
Context? Where's this happening?

**Comment by chrxr** [comment]
Sample-doc-2.docm, line 267-277 in transformed doc

**Comment by nic-gibson** [comment]
15italic is a character style. Can only be treated as such in the code. Nothing to fix here.
