### ISSUE TITLE
zip problems on oxygen pc

### ISSUE THREAD

**Issue by andrgosl** [andrgosl/PUK_XProc_Dev#31]
epub xproc  running on PC  Oxygen is updating content files into a version of the epub zip created in an earlier step (containing just meta-inf and mime files), but is not replacing the original zip or inheriting the correct file name. 

We think this is a calabash bug so we should report back (Windows file locking is stricter than mac), but we should be able to fix for now by zipping the package in one step not two.

**Comment by nic-gibson** [comment]
New version of the epub packaging library committed and pushed. Please test
