### ISSUE TITLE
adding part headers

### ISSUE THREAD

**Issue by andrgosl** [andrgosl/PUK_XProc_Dev#32]
got some feedback from al and ellie yesterday that we need to accomodate part titles. Would need a new style to add this behaviour to the xproc scripts which is not yet created. 

Adding issue here so we can track this request.

**Comment by nic-gibson** [comment]
There is already a style for part titles (at least in the spreadsheet). Code to support it is untested though.

**Comment by andrgosl** [comment]
Chris to create part in manuscript and test.

**Comment by andrgosl** [comment]
we think the word style is 01 part head - check with al

**Comment by chrxr** [comment]
Part titles being sucked into chapter above (chapter or preface). All subsequent chapters are then child of first part until next part.
Uploaded new version of penguin-sample-full-edit_new.docx with three parts inserted.

Part title should be styled as h2.EB09SmallCapsLargeHead

**Comment by chrxr** [comment]
Looks like it's 02 Part title

**Comment by nic-gibson** [comment]
Should now be resolved.

**Comment by chrxr** [comment]
Hi Nic,

I'm afraid when using penguin-sample-full-edit_new.docx the DB XML fails validation:

Description: element "part" not allowed here; expected the element end-tag or element "address", "anchor", "annotation"... 

Additionally, conversion to EPUB fails:

Description:  Cannot write more than one result document to the same URI: file:/Applications/oxygen/preface-005chapter.xhtml

**Comment by nic-gibson** [comment]
Hmmm. Not for me.

## nic

Corbas Consulting / @CorbasLtd
Digital Publishing Consultancy and Training
http://www.corbas.co.uk, +44 (0)7718 906817/+44 (0)1273 930765

**Comment by chrxr** [comment]
Are you sure you've pushed the code? I can't see any updates to the xsl or xproc files in the repo.

C

**Comment by chrxr** [comment]
Now generates valid docbook, but on conversion to EPUB loses all chapters between end of frontmatter and notes page.

**Comment by chrxr** [comment]
According to the current EPUB specs, part title pages should be included in the EPUB. I can't remember how good the support for page-break-after:always, but we could potentially use it.

**Comment by nic-gibson** [comment]
Complete, checked in and pushed. Please test.
