### ISSUE TITLE
A few styles we've missed somehow

### ISSUE THREAD

**Issue by chrxr** [andrgosl/PUK_XProc_Dev#34]
Seems the latest example didn't have the copyright page and "Other penguin shorts" pages styled. Can these be mapped?
I have updated the version of penguin-sample-full-edit_new.docx on github and am just emailing you the updated stylemap doc. The 4 additional styles are marked NEW in the notes column. Also below for ref.

01FMbythesameauthorHead -- h2.EB04MainHead
01FMbythesameauthorList -- p.EB02BodyTextFullOut
13EMHead -- h5.EB13CopyrightHead
13EMEndNotesFL -- p.EB14CopyrightText

Thanks!

**Comment by chrxr** [comment]
Hi Nic,

01FMbythesameauthorList is being styled as EB14CopyrightText, should be EB02BodyTextFullOut
13EMHead is currently being styled as EBO4MainHead, should be EB13CopyrightHead

Thanks!

**Comment by nic-gibson** [comment]
I've made some changes and removed some hard coded styles that still existed. Could you see what is now not mapping correctly?

**Comment by chrxr** [comment]
All working except for 01FMbythesameauthorlist.
