### ISSUE TITLE
Some things to remove from HTML TOC

### ISSUE THREAD

**Issue by chrxr** [andrgosl/PUK_XProc_Dev#36]
Hi Nic,

We need to remove some more stuff from the HTML TOC:

Cover
Penguin Specials page (the one at the front)
About the author
Copyright page

However they should stay in the NCX

Cheers,
Chris

**Comment by nic-gibson** [comment]
I've done this but I'm really not sure it wil be reliable. There isn't a great deal of information in the docx file (and so the docbook file) to indicate which prefaces/appendices should be in the TOC and which shouldn't. Please test.
