### ISSUE TITLE
"Paragraph followed by line break" style to be added

### ISSUE THREAD

**Issue by chrxr** [andrgosl/PUK_XProc_Dev#37]
Hi Nic,

An additional style is needed to provide a paragraph followed by a line break (acting as a mini-section break without breaking pages). I'm waiting for Al to come back with his desired style name for the word template, then I'll need to map it to a style. Will add to this issues when I know more.

Chris

**Comment by nic-gibson** [comment]
OK. No problem

## nic

Corbas Consulting / @CorbasLtd
Digital Publishing Consultancy and Training
http://www.corbas.co.uk, +44 (0)7718 906817/+44 (0)1273 930765

**Comment by chrxr** [comment]
Hi Nic, we have names!

So the style that has been added to the template is called '04 Space Break'.
This needs to be mapped to the style I am calling p.specialsLastPara

Additionally, there is a need for one further style so that we can style the "Other Penguin Specials" author names differently from the book titles. Style name = '01FM by the same author name', needs to be mapped to p.OtherSpecialsAuthor.

Let me know if you need anything else.

Cheers,
Chris

**Comment by nic-gibson** [comment]
Will get these done over the weekend or possibly on the train from Paris to London tomorrow evening.

**Comment by chrxr** [comment]
Hi Nic, just wondering how things are going with this?

Chris

**Comment by nic-gibson** [comment]
Someone (yeah me) forgot to push. As soon as I'm back with a computer, I'll push it

## nic

Corbas Consulting / @CorbasLtd
Digital Publishing Consultancy and Training
http://www.corbas.co.uk, +44 (0)7718 906817/+44 (0)1273 930765

**Comment by nic-gibson** [comment]
Committed changes. Please test.

**Comment by chrxr** [comment]
Thanks Nic, just waiting for a new version of the template with which to test. Will let you know.
