### ISSUE TITLE
Word Comments

### ISSUE THREAD

**Issue by nic-gibson** [andrgosl/PUK_XProc_Dev#7]
Convert these to DocBook `<remark>` elements or suppress them?

**Comment by andrgosl** [comment]
Not ever seen it used in practice, but sounds sensible glancing at the tdg. 

How does the Oxygen DocBook CSS render? Is it user friendly in author view?

**Comment by andrgosl** [comment]
So if sensible retain comment as remark. If remark is a problem (for Oxygen rendering or output to EPUB), then XML comment would suffice. 

On a related point, if we want to add internal or external hyperlinks - this was actually the instruction in the comment in the test manuscript -  how should we add them in the Word manuscript? Will word add hyperlink and hyperlink to bookmark be treated correctly by the Xproc?

**Comment by nic-gibson** [comment]
I'll check in Oxygen but it's generally suppressed in normal output. I could render it to XML comments as well.

The script should render hyperlinks correctly if they are just entered into the the content.

**Comment by andrgosl** [comment]
Use remark, and Chris to test hyperlinks (external and to bookmark)

**Comment by nic-gibson** [comment]
Fixed in latest version
