### ISSUE TITLE
Line 299 sample-doc-1: Caption el containing para with @role caption

### ISSUE THREAD

**Issue by chrxr** [andrgosl/PUK_XProc_Dev#9]
In line 299 of sample-doc-1 there is a caption element with role=caption. Within this is a para element also with role=caption. Is this duplication necessary. Can the child para element be removed?

**Comment by nic-gibson** [comment]
We could easily lose one of the role attributes but the content model for caption requires a para element.

**Comment by dpawson** [comment]
In docbook, the para element is  normally needed within such as
note/warning etc. Not normally
needed within a caption though.

HTH

On 4 July 2012 16:08, chrxr
reply@reply.github.com
wrote:

> In line 299 of sample-doc-1 there is a caption element with role=caption. Within this is a para element also with role=caption. Is this duplication necessary. Can the child para element be removed?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/andrgosl/PUK_XProc_Dev/issues/9

## 

Dave Pawson
XSLT XSL-FO FAQ.
Docbook FAQ.
http://www.dpawson.co.uk

**Comment by nic-gibson** [comment]
Hi Dave

http://www.docbook.org/tdg5/en/html/caption.html

**Comment by dpawson** [comment]
<mediaobject>
  <textobject><para/></textobject>
<caption>
<para>kdkdkdk</para></caption>

Yes... as with note etc... Sorry, my bad.
(IMHO shouldn't be needed, unless author wants to break up the caption?)

regards

On 4 July 2012 16:40, nicg-corbas
reply@reply.github.com
wrote:

> Hi Dave
> 
> http://www.docbook.org/tdg5/en/html/caption.html
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/andrgosl/PUK_XProc_Dev/issues/9#issuecomment-6762860

## 

Dave Pawson
XSLT XSL-FO FAQ.
Docbook FAQ.
http://www.dpawson.co.uk
